obstacle_range: 5.0
raytrace_range: 15.0 

footprint: [[0.175, 0.15], [0.175, -0.15], [-0.175, -0.15], [-0.175, 0.15]]

footprint_padding: 0.01


max_obstacle_height: 0.6 
min_obstacle_height: 0.0 

observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: laser, topic: /scan1, data_type: LaserScan, clearing: true, marking: true}
